// <auto-generated />
namespace Unreal.FGO.Repostory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cookie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cookie));
        
        string IMigrationMetadata.Id
        {
            get { return "201701141528098_cookie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
