// <auto-generated />
namespace Unreal.FGO.Repostory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_roleuser_game : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_roleuser_game));
        
        string IMigrationMetadata.Id
        {
            get { return "201701100732233_user_role.user_game"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
